### ISSUE TITLE
The hours shown and exported are wrong.

### ISSUE THREAD

**Issue by AlexGagne** [BuonOmo/polyfinal#9]
The hours shown on the website are off by 5h30 and the ones exported are off by 30 minutes. I think there are two issues causing this error:

1. This line:
 15   .utcOffset(-5) // Force Quebec Timezone to avoid strange results
 Which explains the 5 hour difference.
2. The time in /js/data.js has a 30 minutes difference from the actual time. So it's 9h instead of 9h30 and 13h instead of 13h30.

**Comment by BuonOmo** [comment]
Nice, thanks for this precise feedback.  This seem to be easy to fix! Would
you like to make a PR?

**Comment by AlexGagne** [comment]
I can do that.
